version: '3'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5555:5432"
  flask:
    build: .
    environment:
      APP_COLOR: RED
    ports:
      - "4051:5000"


